project_id = "rujvbcxpnzpikkmgdkfs"

[functions.send-reset-code]
verify_jwt = false

[functions.verify-reset-code]
verify_jwt = false

[functions.send-contact-notification]
verify_jwt = false

[functions.translate-bulk]
verify_jwt = true

[functions.send-verification-code]
verify_jwt = false
